---
- name: Install the Packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - nginx
    - php-fpm

# Delete the default nginx configuration
- name: Remove the default nginx configuration
  file:
    state: absent
    path: "{{ item }}"
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default

# Copy the configuration file
- name: Copy the configuration file
  copy:
    src: ./files/nginx/default
    dest: /etc/nginx/sites-available/default

# Create a symbolic link
- name: Create a symbolic link
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link

# Copy All file from folder files to /var/www/html
- name: Copy All file from folder files to /var/www/html
  copy:
    src: ./files/website/
    dest: /var/www/

# Restart the nginx service
- name: Restart the nginx service
  service:
    name: nginx
    state: restarted
